--!nonstrict
-- © 2008 David Given.
-- WordProcess is licensed under the MIT open source license. See the COPYING
-- file in this distribution for the full text.

local untextab = {
	["#"] = "\\#",
	["$"] = "\\$",
	["&"] = "\\&",
	["{"] = "\\{",
	["}"] = "\\}",
	["_"] = "\\_{}",
	["^"] = "\\^{}",
	["~"] = "\\~{}",
	["%"] = "\\%",
	["<"] = "$\\langle$",
	[">"] = "$\\rangle$",
	["\\"] = "$\\backslash$"
}

local function untex(s)
	s = s:gsub("[#$&{}\\_^~%%<>]", untextab)
	return s
end

local style_tab=
{
	["H1"] = {'\\section{',            '}'},
	["H2"] = {'\\subsection{',         '}'},
	["H3"] = {'\\subsubsection{',      '}'},
	["H4"] = {'\\paragraph{',          '}'},
	["P"] =  {'',                      '\n'},
	["L"] =  {'\\item[]{',             '}'},
	["LB"] = {'\\item[\\textbullet]{', '}'},
	["LN"] = {'\\item{',               '}'},
	["Q"] =  {'\\begin{quotation}\n',  '\n\\end{quotation}'},
	["N"] =  {'',                      ''},
	["C"] =  {'\\begin{center}',      '\\end{center}'},
	["V"] =  {'\\begin{quotation}\n',  '\n\\end{quotation}'},
	["RAW"] = {'', ''},
	["PRE"] = {'\\begin{verbatim}\n',  '\n\\end{verbatim}'}
}

local function callback(writer, document)
	local layout = GetDocumentPageLayout(document)
	return ExportFileUsingCallbacks(document,
	{
		prologue = function()
			writer('% !TeX program = pdflatex\n')
			writer('%% This document automatically generated by '..
				'WordProcess '..VERSION..'.\n')
			writer('\\documentclass[', tostring(layout.fontSizePt), 'pt]{article}\n')
			writer('\\usepackage[T1]{fontenc}\n')
			writer('\\usepackage[utf8]{inputenc}\n')
			writer('\\usepackage{setspace, geometry}\n')
			writer('\\geometry{paperwidth=', tostring(layout.pageWidthCm),
				'cm,paperheight=', tostring(layout.pageHeightCm),
				'cm,top=', tostring(layout.marginTopCm),
				'cm,right=', tostring(layout.marginRightCm),
				'cm,bottom=', tostring(layout.marginBottomCm),
				'cm,left=', tostring(layout.marginLeftCm), 'cm}\n')
			writer('\\sloppy\n')
			writer('\\setstretch{', tostring(layout.lineSpacing), '}\n')
			writer('\\begin{document}\n')
			local title = documentSet.name and Leafname(documentSet.name) or
				currentDocument.name
			title = title:gsub("%..-$", "")
			writer('\\title{', untex(title), '}\n')
			writer('\\author{(no author)}\n')
			writer('\\maketitle\n')
		end,

		rawtext = function(s)
			writer(s)
		end,

		text = function(s)
			writer(untex(s))
		end,

		notext = function()
			writer('\\paragraph{}')
		end,

		italic_on = function()
			writer('\\textit{')
		end,

		italic_off = function()
			writer('}')
		end,

		bold_on = function()
			writer('\\textbf{')
		end,

		bold_off = function()
			writer('}')
		end,

		underline_on = function()
			writer('\\underline{')
		end,

		underline_off = function()
			writer('}')
		end,

		list_start = function(n)
			writer('\\begin{enumerate}\n')
		end,

		list_end = function(n)
			writer('\\end{enumerate}\n')
		end,

		paragraph_start = function(para)
			if para.style == "Q" or para.style == "V" or
				para.style == "N" or para.style == "C" then
				writer('\\begin{quotation}\\fontsize{',
					tostring(layout.specialFontSizePt), '}{',
					tostring(layout.specialFontSizePt * layout.specialLineSpacing),
					'}\\selectfont\\setstretch{',
					tostring(layout.specialLineSpacing), '}\n')
			else
				writer(style_tab[para.style][1] or "")
			end
		end,

		paragraph_end = function(para)
			if para.style == "Q" or para.style == "V" or
				para.style == "N" or para.style == "C" then
				writer('\n\\end{quotation}')
			else
				writer(style_tab[para.style][2] or "")
			end
			writer('\n')
		end,

		epilogue = function()
			writer('\\end{document}\n')
		end
	})
end

function Cmd.ExportLatexFile(filename)
	return ExportFileWithUI(filename, "Export LaTeX File", ".tex",
		callback)
end

function Cmd.ExportToLatexString()
	return ExportToString(currentDocument, callback)
end
