--!nonstrict
loadfile("tests/testsuite.lua")()

local data = [[
This is paragraph 1.
This is 2.

This is 4 (3 was blank).
]]

local document = Cmd.ImportTextString(data)

local expected = [[
% !TeX program = pdflatex
%% This document automatically generated by WordProcess @@@.
\documentclass[12pt]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{setspace, geometry}
\geometry{paperwidth=21.0cm,paperheight=29.7cm,top=2.5cm,right=2.5cm,bottom=2.5cm,left=2.5cm}
\sloppy
\setstretch{1.15}
\begin{document}
\title{imported}
\author{(no author)}
\maketitle
This is paragraph 1.

This is 2.

\paragraph{}

This is 4 (3 was blank).

\end{document}
]]
expected = expected:gsub("@@@", VERSION)

documentSet:addDocument(document, "imported")
documentSet:setCurrent("imported")
local output = Cmd.ExportToLatexString()
AssertEquals(expected, output)


document = Cmd.ImportTextString(9)
document = Cmd.ImportTextString("no trailing newline")
documentSet:addDocument(document, "imported")
documentSet:setCurrent("imported")
AssertTableEquals({"no", "trailing", "newline"}, currentDocument[1])
