--!nonstrict
loadfile("tests/testsuite.lua")()

local document = Cmd.ImportODTFile("testdocs/testdoc.odt")

local expected = [[
%% This document automatically generated by WordProcess @@@.
\documentclass[12pt]{article}
\usepackage{xunicode, setspace, xltxtra, geometry}
\geometry{paperwidth=21.0cm,paperheight=29.7cm,top=2.5cm,right=2.5cm,bottom=2.5cm,left=2.5cm}
\sloppy
\setstretch{1.15}
\begin{document}
\title{testdoc.odt}
\author{(no author)}
\maketitle
\section{Heading 1}
This is \textbf{bold }\textit{\textbf{bolditalic }}\textit{\textbf{\underline{bolditalicunderline }}}\textit{\underline{italicunderline }}\underline{underline} }plain

normal text

\begin{enumerate}
\item[\textbullet]{bullet}
\item[\textbullet]{bullet}
\item[\textbullet]{no bullet}
\item[\textbullet]{no bullet}
\item{number}
\item{number}
\item[\textbullet]{nothing}
\item{number}
\item[\textbullet]{bullet}
\end{enumerate}
normal text

\end{document}
]]
expected = expected:gsub("@@@", VERSION)

documentSet:setCurrent("testdoc.odt")
local output = Cmd.ExportToLatexString()
AssertEquals(expected, output)

